version: '3.9'
services:
  db:
    container_name: route-finder-api-db
    image: postgres:15-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=route-finder-api
      - POSTGRES_DB=route-finder-api
      - POSTGRES_USER=route-finder-api
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U route-finder-api" ]
      interval: 10s
      timeout: 5s
      retries: 5
  app:
    container_name: route-finder-api-app
    image: route-finder-api:latest
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/route-finder-api
      - SPRING_DATASOURCE_USERNAME=route-finder-api
      - SPRING_DATASOURCE_PASSWORD=route-finder-api
    depends_on:
      db:
        condition: service_healthy
